name: Documentation

on:
  push:
    branches: 'master'
    paths-ignore: 'docs/**'

env:
  RUST_BACKTRACE: 1
  RUSTDOCFLAGS: "--generate-link-to-definition -Zunstable-options"

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: '15'

      - name: Set up the environment
        run: python x.py setup

      - name: Generate documentation.
        run: python x.py doc

      - name: Publish to GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc/
          keep_files: false
          destination_dir: doc

      - name: Squash deploy commits of GitHub pages
        run: |
          git remote update
          git checkout origin/gh-pages
          git reset origin/gh-pages-base
          git commit -am "deploy: ${GITHUB_SHA}"
          git push --set-upstream origin gh-pages
